name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy_dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'http://gordao.com.br'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Hello, dev!
        
  deploy_hmg:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: hmg
      url: 'http://gordao.com.br'
    needs: deploy_dev
    steps:
      - name: Piloteado
        uses: actions/checkout@v2
        
      - name: Run a one-line script
        run: echo AAAAAAAAAAA TO COM DEPRESSÃO
      
      - name: Send Nelson to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/rotten-potatoes:${{ github.sha }}
          registry: docker.io
          dockerfile: ./src/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Azure Login
      - uses: azure/login@v1
        with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Azure Context
      - uses: azure/aks-set-context@v3
        with:
           resource-group: 'aks_tf_rg'
           cluster-name: 'devops-patrick-aks'
          
      - name: Create secret in Kubernetes cluster
        uses: Azure/k8s-create-secret@v3.0
        with:
          # Choose the target Kubernetes namespace. If the namespace is not provided, the commands will run in the default namespace.
          #namespace: 'github-actions'
          # Type of Kubernetes secret. Defaults to 'kubernetes.io/dockerconfigjson'.
          #secret-type: # optional, default is kubernetes.io/dockerconfigjson
          # Name of the secret. You can use this secret name in the Kubernetes YAML configuration file.
          secret-name: docker-image-pull-secret
          # Container Registry URL
          container-registry-url: https://index.docker.io/v2/
          # Container Registry user name
          container-registry-username: ${{ secrets.DOCKER_USERNAME }}
          # Container Registry password
          container-registry-password: ${{ secrets.DOCKER_PASSWORD }}
          
          
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.3
        with:
          # Choose the target Kubernetes namespace. If the namespace is not provided, the commands will run in the default namespace.
          namespace: 'github-actions'
          # Path to the manifest files which will be used for deployment.
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
          # Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files Example: contosodemo.azurecr.io/helloworld:test
          images: ${{ secrets.DOCKER_USERNAME }}/rotten-potatoes:${{ github.sha }}
          # Name of a docker-registry secret that has already been set up within the cluster. Each of these secret names are added under imagePullSecrets field for the workloads found in the input manifest files
          imagepullsecrets: docker-image-pull-secret
          action: deploy


        
  deploy_prd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: prd
      url: 'http://gordao.com.br'
    needs: deploy_hmg
    steps:
      - name: Run a one-line script
        run: echo Hello, prd!


